{% set name = "grove" %}
{% set pip_name = "quantum-grove" %}
{% set version = "1.7.0" %}
{% set sha256 = "a563efa7471abb932a1e9e4ab9f01aaa2b3136cda5854e0be3af35f334b88d7e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pip_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - numpy
    - pytest-runner
  run:
    - python
    - numpy
    - qutip
    - pyquil
    - networkx
    - scipy
    - funcsigs

test:
  imports:
    - grove
    - grove.amplification
    - grove.bernstein_vazirani
    - grove.deutsch_jozsa
    - grove.ising
    - grove.pyqaoa
    - grove.pyvqe
    - grove.qft
    - grove.simon
    - grove.utils
    - grove.tomography

about:
  home: https://github.com/rigetticomputing/grove
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'A collection of quantum algorithms built using pyQuil and Forest'

  description: |
    A collection of quantum algorithms built using pyQuil and Forest.
  doc_url: http://grove-docs.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/grove

extra:
  recipe-maintainers:
    - ntezak
