travis:
  secure:
    BINSTAR_TOKEN: ITWwzDHmq3tXkPaxDJLIAGTK0Mp7RHpNLVsgl3L1nvbBTI8KrMm2n8FoY+QGdI3qmBl+tlKEmCVqd9AyeS+RLKHRjm0WFaXLi/tynroPHsLUnTE6r8+H10kqyyV/atfdsLThvB8KtD43cbV2E8c7XseEJN1BakWfLh6CZRvtWTISPh+JaVC0q21xtqVS4y+RiFjwwvkCiPJnd9T2cNtZVmmLgfj/fhjg8BpABZBI8iW4NX5UB+urA9HbX7kDqJtCeEV4s0GIxkcIqUJN1utP9RaFWhHoF/ESUTCz9x2H96tWKOj6qCXFLQPXGtAH25XKoUdNbH40o4nTHIWQwRB6TcwVOtoLjiKnO3qzOpYeGwyiYeYlcwaGRjuj2Rk0HBk0qWoel7DCJ9xVbkFpFJsJz7+7wRCfvsZQoIafT+PwzoKqQr7Yk5OniQlZwiefWYHB6Hk3sd61uN/RlFHTaGSCxIfjSeqhZaD0DxXhAaig3jr/VtxwyR0ckWZE1NVOGaQiUzTgG5AwZ0pLPnNs/+d5TZj70O7s/KeTS9K3dvFHhYd6J7m459VtSFsZmuGDrd2ZgPj6/+hRk0h1XBOY2lKkcV7+7kasnnI7arp75Xur+/fHE7Cxa6h/5jcYRpblEmRO/CjLF7S+laPO+wNkBbLv5S/NQ+Pq9Oi64KKlEV6k3d0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
