travis:
  secure:
    BINSTAR_TOKEN: CSY92DuL4I03t8kOjGmqoLCzCLN2qRjMJMi11VzaK3fe4Mduqmbw273ROK4m+rkhA7buxcFy3915AQ4IoWIot04L1UJJKUpy7Qm9T9CuqOLtUTnAlT7soYdbkTeCtRZM67epxOgqnBHYCYvMXzT/3SNLrWe53w5luKxiLgnqCrPidHPdFPOdvxp45VCpDgmt7zzvJ33ApnSxAbjLVG697R6MUOzFOiI+whkbbMEqKg46TbaazHlqT2r8SIqTDcX43BSQasuIB+HF08XsvbmB8P6JTpKsYpcabvUFEW95Ju/vfPf6gFfhXuWta2936aQ2GaeVT3pTAzjZWchjF5VPUO4FWiaz6IDyLEn1qaK9S5R1ZCitM9G5sCpUdnfzqKGgDuz4cjC1iTAu9GIzZEWXR8Q3JvR25kbD1FFwQfG1QLGinW/Un0UXZUtofDSdM9qXa3047g1CITXhBAxX1HLleV17XK5Xhsb/L7wmjrl5heraoxLhrXjAAwLntl5Sk4BWQ11xF/FpGOOijtT8IqIYiwYTs/BMriEB/PPsbdemJW5mkPfbucUzW8Czxi+YGYT/x/OXlUNC8ZPJAtMdcoGw1klCxyZoDQPYy+PnoNhbIGZsjoIhn8Ocg06hs34eHOXA20scWyPazIFuFmJmR50MsC6yb8EChXDfZ008Xyb5OJI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
